#### 开发环境配置文件
#### 设置项目启动端口号
server:
  port: 80
spring:
  application:
    name: addrook-backend
  #### 开启 spring bean id override机制
  main:
    allow-bean-definition-overriding: true
  #### 配置 datasource 信息
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/addrook_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 15610570603wh
    #### 使用 Druid 数据连接池技术
    type: com.alibaba.druid.pool.DruidDataSource
    #### 配置 Druid 信息
    druid:
      min-idle: 3
      max-active: 15
      initial-size: 5
      min-evictable-idle-time-millis: 30000
      max-evictable-idle-time-millis: 60000
      #### 配置 Druid 监控信息
      stat-view-servlet:
        #### 开启监控平台
        enabled: true
        #### 登录监控系统请求地址
        url-pattern: /druid/*
        #### 配置监控系统访问白名单 ip 地址
        allow: 127.0.0.1
        #### 配置访问用户名和地址
        login-username: druid
        login-password: 123456
        #### 能否重置数据
        reset-enable: false
      ####配置过滤规则
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,/*.css,*.ico,/duirid/*"